package generator



import (
	"sort"
	"strings"
	"testing"
)

func OldConcatSortedMap(m map[string]string, sep string) string {
	keys := make([]string, 0)
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	s := ""
	for _, k := range keys {
		s += m[k] + sep
	}
	return s
}

func OptBuilderConcatSortedMap(m map[string]string, sep string) string {
	var builder strings.Builder
	l := len(m)
	keys := make([]string, 0, l)
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, val := range keys {
		builder.WriteString(m[val] + sep)
	}
	return builder.String()
}

func BenchmarkOld(b *testing.B) {
	testMap := map[string]string{
		"test 0" :"test b",
		"test 1" :"test c",
		"test 2" :"test d",
		"test 3" :"test e",
		"test 4" :"test f",
		"test 5" :"test g",
		"test 6" :"test h",
		"test 7" :"test i",
		"test 8" :"test j",
		"test 9" :"test k",
		"test 10" :"test l",
		"test 11" :"test m",
		"test 12" :"test n",
		"test 13" :"test o",
		"test 14" :"test p",
		"test 15" :"test q",
		"test 16" :"test r",
		"test 17" :"test s",
		"test 18" :"test t",
		"test 19" :"test u",
		"test 20" :"test v",
		"test 21" :"test w",
		"test 22" :"test x",
		"test 23" :"test y",
		"test 24" :"test z",
		"test 25" :"test {",
		"test 26" :"test |",
		"test 27" :"test }",
		"test 28" :"test ¡",
		"test 29" :"test ¢",
		"test 30" :"test £",
		"test 31" :"test ¤",
		"test 32" :"test ¥",
		"test 33" :"test ¦",
		"test 34" :"test §",
		"test 35" :"test ¨",
		"test 36" :"test ©",
		"test 37" :"test ª",
		"test 38" :"test «",
		"test 39" :"test ¬",
		"test 40" :"test ­",
		"test 41" :"test ®",
		"test 42" :"test ¯",
		"test 43" :"test °",
		"test 44" :"test ±",
		"test 45" :"test ²",
		"test 46" :"test ³",
		"test 47" :"test ´",
		"test 48" :"test µ",
		"test 49" :"test ¶",
		"test 50" :"test ·",
		"test 51" :"test ¸",
		"test 52" :"test ¹",
		"test 53" :"test º",
		"test 54" :"test »",
		"test 55" :"test ¼",
		"test 56" :"test ½",
		"test 57" :"test ¾",
		"test 58" :"test ¿",
		"test 59" :"test À",
		"test 60" :"test Á",
		"test 61" :"test Â",
		"test 62" :"test Ã",
		"test 63" :"test Ä",
		"test 64" :"test Å",
		"test 65" :"test Æ",
		"test 66" :"test Ç",
		"test 67" :"test È",
		"test 68" :"test É",
		"test 69" :"test Ê",
		"test 70" :"test Ë",
		"test 71" :"test Ì",
		"test 72" :"test Í",
		"test 73" :"test Î",
		"test 74" :"test Ï",
		"test 75" :"test Ð",
		"test 76" :"test Ñ",
		"test 77" :"test Ò",
		"test 78" :"test Ó",
		"test 79" :"test Ô",
		"test 80" :"test Õ",
		"test 81" :"test Ö",
		"test 82" :"test ×",
		"test 83" :"test Ø",
		"test 84" :"test Ù",
		"test 85" :"test Ú",
		"test 86" :"test Û",
		"test 87" :"test Ü",
		"test 88" :"test Ý",
		"test 89" :"test Þ",
		"test 90" :"test ß",
		"test 91" :"test à",
		"test 92" :"test á",
		"test 93" :"test â",
		"test 94" :"test ã",
		"test 95" :"test ä",
		"test 96" :"test å",
		"test 97" :"test æ",
		"test 98" :"test ç",
		"test 99" :"test è",
	}
	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		OldConcatSortedMap(testMap, "_")
	}
	b.StopTimer()

}

func BenchmarkNew(b *testing.B) {
	testMap := map[string]string{
		"test 0" :"test b",
		"test 1" :"test c",
		"test 2" :"test d",
		"test 3" :"test e",
		"test 4" :"test f",
		"test 5" :"test g",
		"test 6" :"test h",
		"test 7" :"test i",
		"test 8" :"test j",
		"test 9" :"test k",
		"test 10" :"test l",
		"test 11" :"test m",
		"test 12" :"test n",
		"test 13" :"test o",
		"test 14" :"test p",
		"test 15" :"test q",
		"test 16" :"test r",
		"test 17" :"test s",
		"test 18" :"test t",
		"test 19" :"test u",
		"test 20" :"test v",
		"test 21" :"test w",
		"test 22" :"test x",
		"test 23" :"test y",
		"test 24" :"test z",
		"test 25" :"test {",
		"test 26" :"test |",
		"test 27" :"test }",
		"test 28" :"test ¡",
		"test 29" :"test ¢",
		"test 30" :"test £",
		"test 31" :"test ¤",
		"test 32" :"test ¥",
		"test 33" :"test ¦",
		"test 34" :"test §",
		"test 35" :"test ¨",
		"test 36" :"test ©",
		"test 37" :"test ª",
		"test 38" :"test «",
		"test 39" :"test ¬",
		"test 40" :"test ­",
		"test 41" :"test ®",
		"test 42" :"test ¯",
		"test 43" :"test °",
		"test 44" :"test ±",
		"test 45" :"test ²",
		"test 46" :"test ³",
		"test 47" :"test ´",
		"test 48" :"test µ",
		"test 49" :"test ¶",
		"test 50" :"test ·",
		"test 51" :"test ¸",
		"test 52" :"test ¹",
		"test 53" :"test º",
		"test 54" :"test »",
		"test 55" :"test ¼",
		"test 56" :"test ½",
		"test 57" :"test ¾",
		"test 58" :"test ¿",
		"test 59" :"test À",
		"test 60" :"test Á",
		"test 61" :"test Â",
		"test 62" :"test Ã",
		"test 63" :"test Ä",
		"test 64" :"test Å",
		"test 65" :"test Æ",
		"test 66" :"test Ç",
		"test 67" :"test È",
		"test 68" :"test É",
		"test 69" :"test Ê",
		"test 70" :"test Ë",
		"test 71" :"test Ì",
		"test 72" :"test Í",
		"test 73" :"test Î",
		"test 74" :"test Ï",
		"test 75" :"test Ð",
		"test 76" :"test Ñ",
		"test 77" :"test Ò",
		"test 78" :"test Ó",
		"test 79" :"test Ô",
		"test 80" :"test Õ",
		"test 81" :"test Ö",
		"test 82" :"test ×",
		"test 83" :"test Ø",
		"test 84" :"test Ù",
		"test 85" :"test Ú",
		"test 86" :"test Û",
		"test 87" :"test Ü",
		"test 88" :"test Ý",
		"test 89" :"test Þ",
		"test 90" :"test ß",
		"test 91" :"test à",
		"test 92" :"test á",
		"test 93" :"test â",
		"test 94" :"test ã",
		"test 95" :"test ä",
		"test 96" :"test å",
		"test 97" :"test æ",
		"test 98" :"test ç",
		"test 99" :"test è",
	}
	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		concatSortedMap(testMap, "_")
	}
	b.StopTimer()
}
func BenchmarkNewBuilder(b *testing.B) {
	testMap := map[string]string{
		"test 0" :"test b",
		"test 1" :"test c",
		"test 2" :"test d",
		"test 3" :"test e",
		"test 4" :"test f",
		"test 5" :"test g",
		"test 6" :"test h",
		"test 7" :"test i",
		"test 8" :"test j",
		"test 9" :"test k",
		"test 10" :"test l",
		"test 11" :"test m",
		"test 12" :"test n",
		"test 13" :"test o",
		"test 14" :"test p",
		"test 15" :"test q",
		"test 16" :"test r",
		"test 17" :"test s",
		"test 18" :"test t",
		"test 19" :"test u",
		"test 20" :"test v",
		"test 21" :"test w",
		"test 22" :"test x",
		"test 23" :"test y",
		"test 24" :"test z",
		"test 25" :"test {",
		"test 26" :"test |",
		"test 27" :"test }",
		"test 28" :"test ¡",
		"test 29" :"test ¢",
		"test 30" :"test £",
		"test 31" :"test ¤",
		"test 32" :"test ¥",
		"test 33" :"test ¦",
		"test 34" :"test §",
		"test 35" :"test ¨",
		"test 36" :"test ©",
		"test 37" :"test ª",
		"test 38" :"test «",
		"test 39" :"test ¬",
		"test 40" :"test ­",
		"test 41" :"test ®",
		"test 42" :"test ¯",
		"test 43" :"test °",
		"test 44" :"test ±",
		"test 45" :"test ²",
		"test 46" :"test ³",
		"test 47" :"test ´",
		"test 48" :"test µ",
		"test 49" :"test ¶",
		"test 50" :"test ·",
		"test 51" :"test ¸",
		"test 52" :"test ¹",
		"test 53" :"test º",
		"test 54" :"test »",
		"test 55" :"test ¼",
		"test 56" :"test ½",
		"test 57" :"test ¾",
		"test 58" :"test ¿",
		"test 59" :"test À",
		"test 60" :"test Á",
		"test 61" :"test Â",
		"test 62" :"test Ã",
		"test 63" :"test Ä",
		"test 64" :"test Å",
		"test 65" :"test Æ",
		"test 66" :"test Ç",
		"test 67" :"test È",
		"test 68" :"test É",
		"test 69" :"test Ê",
		"test 70" :"test Ë",
		"test 71" :"test Ì",
		"test 72" :"test Í",
		"test 73" :"test Î",
		"test 74" :"test Ï",
		"test 75" :"test Ð",
		"test 76" :"test Ñ",
		"test 77" :"test Ò",
		"test 78" :"test Ó",
		"test 79" :"test Ô",
		"test 80" :"test Õ",
		"test 81" :"test Ö",
		"test 82" :"test ×",
		"test 83" :"test Ø",
		"test 84" :"test Ù",
		"test 85" :"test Ú",
		"test 86" :"test Û",
		"test 87" :"test Ü",
		"test 88" :"test Ý",
		"test 89" :"test Þ",
		"test 90" :"test ß",
		"test 91" :"test à",
		"test 92" :"test á",
		"test 93" :"test â",
		"test 94" :"test ã",
		"test 95" :"test ä",
		"test 96" :"test å",
		"test 97" :"test æ",
		"test 98" :"test ç",
		"test 99" :"test è",
	}
	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		OptBuilderConcatSortedMap(testMap, "_")
	}
	b.StopTimer()
}

func TestConcatSortedMap(t *testing.T) {
	testMap := map[string]string{
		"test 0" :"test b",
		"test 1" :"test c",
		"test 2" :"test d",
		"test 3" :"test e",
		"test 4" :"test f",
		"test 5" :"test g",
		"test 6" :"test h",
		"test 7" :"test i",
		"test 8" :"test j",
		"test 9" :"test k",
		"test 10" :"test l",
		"test 11" :"test m",
		"test 12" :"test n",
		"test 13" :"test o",
		"test 14" :"test p",
		"test 15" :"test q",
		"test 16" :"test r",
		"test 17" :"test s",
		"test 18" :"test t",
		"test 19" :"test u",
		"test 20" :"test v",
		"test 21" :"test w",
		"test 22" :"test x",
		"test 23" :"test y",
		"test 24" :"test z",
		"test 25" :"test {",
		"test 26" :"test |",
		"test 27" :"test }",
		"test 28" :"test ¡",
		"test 29" :"test ¢",
		"test 30" :"test £",
		"test 31" :"test ¤",
		"test 32" :"test ¥",
		"test 33" :"test ¦",
		"test 34" :"test §",
		"test 35" :"test ¨",
		"test 36" :"test ©",
		"test 37" :"test ª",
		"test 38" :"test «",
		"test 39" :"test ¬",
		"test 40" :"test ­",
		"test 41" :"test ®",
		"test 42" :"test ¯",
		"test 43" :"test °",
		"test 44" :"test ±",
		"test 45" :"test ²",
		"test 46" :"test ³",
		"test 47" :"test ´",
		"test 48" :"test µ",
		"test 49" :"test ¶",
		"test 50" :"test ·",
		"test 51" :"test ¸",
		"test 52" :"test ¹",
		"test 53" :"test º",
		"test 54" :"test »",
		"test 55" :"test ¼",
		"test 56" :"test ½",
		"test 57" :"test ¾",
		"test 58" :"test ¿",
		"test 59" :"test À",
		"test 60" :"test Á",
		"test 61" :"test Â",
		"test 62" :"test Ã",
		"test 63" :"test Ä",
		"test 64" :"test Å",
		"test 65" :"test Æ",
		"test 66" :"test Ç",
		"test 67" :"test È",
		"test 68" :"test É",
		"test 69" :"test Ê",
		"test 70" :"test Ë",
		"test 71" :"test Ì",
		"test 72" :"test Í",
		"test 73" :"test Î",
		"test 74" :"test Ï",
		"test 75" :"test Ð",
		"test 76" :"test Ñ",
		"test 77" :"test Ò",
		"test 78" :"test Ó",
		"test 79" :"test Ô",
		"test 80" :"test Õ",
		"test 81" :"test Ö",
		"test 82" :"test ×",
		"test 83" :"test Ø",
		"test 84" :"test Ù",
		"test 85" :"test Ú",
		"test 86" :"test Û",
		"test 87" :"test Ü",
		"test 88" :"test Ý",
		"test 89" :"test Þ",
		"test 90" :"test ß",
		"test 91" :"test à",
		"test 92" :"test á",
		"test 93" :"test â",
		"test 94" :"test ã",
		"test 95" :"test ä",
		"test 96" :"test å",
		"test 97" :"test æ",
		"test 98" :"test ç",
		"test 99" :"test è",
	}

	if OldConcatSortedMap(testMap, "_")!=concatSortedMap(testMap, "_"){
		t.Error("Functions don't do the same thing")
	}
}

func TestConcatBuilderSortedMap(t *testing.T) {
	testMap := map[string]string{
		"test 0" :"test b",
		"test 1" :"test c",
		"test 2" :"test d",
		"test 3" :"test e",
		"test 4" :"test f",
		"test 5" :"test g",
		"test 6" :"test h",
		"test 7" :"test i",
		"test 8" :"test j",
		"test 9" :"test k",
		"test 10" :"test l",
		"test 11" :"test m",
		"test 12" :"test n",
		"test 13" :"test o",
		"test 14" :"test p",
		"test 15" :"test q",
		"test 16" :"test r",
		"test 17" :"test s",
		"test 18" :"test t",
		"test 19" :"test u",
		"test 20" :"test v",
		"test 21" :"test w",
		"test 22" :"test x",
		"test 23" :"test y",
		"test 24" :"test z",
		"test 25" :"test {",
		"test 26" :"test |",
		"test 27" :"test }",
		"test 28" :"test ¡",
		"test 29" :"test ¢",
		"test 30" :"test £",
		"test 31" :"test ¤",
		"test 32" :"test ¥",
		"test 33" :"test ¦",
		"test 34" :"test §",
		"test 35" :"test ¨",
		"test 36" :"test ©",
		"test 37" :"test ª",
		"test 38" :"test «",
		"test 39" :"test ¬",
		"test 40" :"test ­",
		"test 41" :"test ®",
		"test 42" :"test ¯",
		"test 43" :"test °",
		"test 44" :"test ±",
		"test 45" :"test ²",
		"test 46" :"test ³",
		"test 47" :"test ´",
		"test 48" :"test µ",
		"test 49" :"test ¶",
		"test 50" :"test ·",
		"test 51" :"test ¸",
		"test 52" :"test ¹",
		"test 53" :"test º",
		"test 54" :"test »",
		"test 55" :"test ¼",
		"test 56" :"test ½",
		"test 57" :"test ¾",
		"test 58" :"test ¿",
		"test 59" :"test À",
		"test 60" :"test Á",
		"test 61" :"test Â",
		"test 62" :"test Ã",
		"test 63" :"test Ä",
		"test 64" :"test Å",
		"test 65" :"test Æ",
		"test 66" :"test Ç",
		"test 67" :"test È",
		"test 68" :"test É",
		"test 69" :"test Ê",
		"test 70" :"test Ë",
		"test 71" :"test Ì",
		"test 72" :"test Í",
		"test 73" :"test Î",
		"test 74" :"test Ï",
		"test 75" :"test Ð",
		"test 76" :"test Ñ",
		"test 77" :"test Ò",
		"test 78" :"test Ó",
		"test 79" :"test Ô",
		"test 80" :"test Õ",
		"test 81" :"test Ö",
		"test 82" :"test ×",
		"test 83" :"test Ø",
		"test 84" :"test Ù",
		"test 85" :"test Ú",
		"test 86" :"test Û",
		"test 87" :"test Ü",
		"test 88" :"test Ý",
		"test 89" :"test Þ",
		"test 90" :"test ß",
		"test 91" :"test à",
		"test 92" :"test á",
		"test 93" :"test â",
		"test 94" :"test ã",
		"test 95" :"test ä",
		"test 96" :"test å",
		"test 97" :"test æ",
		"test 98" :"test ç",
		"test 99" :"test è",
	}

	if OldConcatSortedMap(testMap, "_")!=OptBuilderConcatSortedMap(testMap, "_"){
		t.Error("Functions don't do the same thing")
	}
}